name = "catechismecatholique"
compatibility_date = "2026-05-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "SEARCH_INDEX"
id = "f6806983770a464b9b657f0f9503a2b3"
preview_id = "29450af80b784bdba6493b3eda25707f"
