name = "catechismecatholique"
compatibility_date = "2026-05-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "SEARCH_INDEX"
id = "REPLACE_WITH_KV_ID_AFTER_CREATING"
preview_id = "REPLACE_WITH_KV_PREVIEW_ID"
