// Cluster taxonomy for the merged glossary. Each head-word lands in 1 or 2
// clusters. Auto-assignment uses keyword matches against the head-word and
// its sub-entry labels; the OVERRIDES below pin the borderline cases.
//
// After running glossary builds across the parsed data, the list was tuned
// to 12 clusters that map cleanly onto the catechism's actual content
// distribution (the original 11-cluster proposal merged "vocabulaire
// technique" into the relevant theological clusters, then split off a
// dedicated "écriture" cluster — biblical material is too distinctive to
// share a bucket with "tradition").

export type ClusterId =
	| 'trinite'
	| 'christ'
	| 'esprit-saint'
	| 'eglise'
	| 'sacrements'
	| 'liturgie'
	| 'morale'
	| 'priere'
	| 'ecriture'
	| 'marie-saints'
	| 'fins-dernieres'
	| 'creation-homme';

export interface Cluster {
	id: ClusterId;
	label: string;
	short: string;
	description: string;
	order: number;
}

export const CLUSTERS: Cluster[] = [
	{
		id: 'trinite',
		label: 'Dieu et la Trinité',
		short: 'Trinité',
		description:
			'Mystère de Dieu un en trois Personnes : Père, Fils et Esprit Saint, ses attributs et son dessein de salut.',
		order: 1
	},
	{
		id: 'christ',
		label: 'Le Christ',
		short: 'Christ',
		description:
			'Incarnation, vie publique, Passion, Résurrection, Ascension et titres du Christ Jésus.',
		order: 2
	},
	{
		id: 'esprit-saint',
		label: "L'Esprit Saint",
		short: 'Esprit Saint',
		description:
			"L'Esprit du Père et du Fils, ses dons, son action dans l'Église et dans la vie chrétienne.",
		order: 3
	},
	{
		id: 'creation-homme',
		label: 'Création et personne humaine',
		short: 'Création & homme',
		description:
			"La création, l'homme à l'image de Dieu, le corps et l'âme, la chute et la condition humaine.",
		order: 4
	},
	{
		id: 'eglise',
		label: 'Église et ministères',
		short: 'Église',
		description:
			"L'Église comme Corps du Christ et peuple de Dieu, sa hiérarchie, son magistère, ses ministères.",
		order: 5
	},
	{
		id: 'sacrements',
		label: 'Sacrements',
		short: 'Sacrements',
		description: 'Les sept sacrements et leur grâce dans la vie de la foi.',
		order: 6
	},
	{
		id: 'liturgie',
		label: 'Liturgie',
		short: 'Liturgie',
		description: 'Célébration du mystère chrétien, année liturgique, signes et symboles sacrés.',
		order: 7
	},
	{
		id: 'morale',
		label: 'Vie morale',
		short: 'Morale',
		description: 'Loi et grâce, conscience, vertus, péchés, commandements, vie en Christ.',
		order: 8
	},
	{
		id: 'priere',
		label: 'Prière',
		short: 'Prière',
		description: 'Vie de prière, formes de prière, le Notre Père.',
		order: 9
	},
	{
		id: 'ecriture',
		label: 'Écriture et Révélation',
		short: 'Écriture',
		description:
			'Bible, Tradition, Révélation, livres de l\'Ancien et du Nouveau Testament, exégèse.',
		order: 10
	},
	{
		id: 'marie-saints',
		label: 'Marie et les saints',
		short: 'Marie & saints',
		description: 'La Vierge Marie, communion des saints, anges, dévotion.',
		order: 11
	},
	{
		id: 'fins-dernieres',
		label: 'Fins dernières',
		short: 'Fins dernières',
		description: 'Mort, jugement, Ciel, Purgatoire, Enfer, résurrection des morts, vie éternelle.',
		order: 12
	}
];

export const CLUSTER_BY_ID = new Map(CLUSTERS.map((c) => [c.id, c]));

// Keywords (lowercased, diacritic-stripped) that suggest a cluster when found
// in a head-word or any of its sub-entry labels. Each match adds a vote;
// final assignment = clusters whose votes are above 0, capped at top 2.
export const CLUSTER_KEYWORDS: Record<ClusterId, string[]> = {
	trinite: [
		'dieu',
		'pere',
		'trinite',
		'trinitaire',
		'createur',
		'tout puissant',
		'verbe',
		'monotheisme',
		'polytheisme',
		'agnosticisme',
		'atheisme',
		'gnose',
		'dualisme',
		'kyrios',
		'sacre',
		'jehovah',
		'yhwh'
	],
	christ: [
		'christ',
		'jesus',
		'incarnation',
		'passion',
		'resurrection',
		'crucifixion',
		'ascension',
		'messie',
		'fils de dieu',
		'fils unique',
		'redempteur',
		'sauveur'
	],
	'esprit-saint': ['esprit saint', 'esprit', 'pentecote', 'don', 'charisme', 'paraclet'],
	'creation-homme': [
		'creation',
		'homme',
		'femme',
		'corps',
		'ame',
		'personne',
		'image de dieu',
		'genese',
		'adam',
		'eve',
		'chute',
		'peche originel',
		'sexualite',
		'travail'
	],
	eglise: [
		'eglise',
		'magistere',
		'pape',
		'eveque',
		'pretre',
		'diacre',
		'concile',
		'schisme',
		'heresie',
		'apostolique',
		'apostolicite',
		'catholicite',
		'communion',
		'collegialite',
		'ministre',
		'hierarchie',
		'laic',
		'clerge',
		'diaconie',
		'ermite',
		'institut',
		'missionnaire',
		'religiosite',
		'votum',
		'orthodoxie',
		'orthodoxe',
		'oecumenisme',
		'oecumenique',
		'paroisse',
		'diocese',
		'cathedrale',
		'chretiens'
	],
	sacrements: [
		'sacrement',
		'bapteme',
		'confirmation',
		'eucharistie',
		'penitence',
		'reconciliation',
		'onction',
		'ordre',
		'mariage',
		'consecration',
		'absolution',
		'transubstantiation',
		'communion eucharistique'
	],
	liturgie: [
		'liturgie',
		'liturgique',
		'messe',
		'celebration',
		'rite',
		'rituel',
		'office',
		'priere liturgique',
		'autel',
		'epiclese',
		'anaphore',
		'anamnese',
		'dimanche',
		'fete',
		'avent',
		'careme',
		'paques',
		'noel',
		'ambon',
		'baptistere',
		'banquet',
		'cimetiere',
		'collecte',
		'encens',
		'epiphanie',
		'myron',
		'procession',
		'azyme',
		'sanctuaire',
		'sacramental',
		'iconographie',
		'icone'
	],
	morale: [
		'vertu',
		'peche',
		'conscience',
		'loi',
		'commandement',
		'decalogue',
		'beatitude',
		'morale',
		'justice',
		'charite',
		'esperance',
		'foi',
		'tempérance',
		'force',
		'prudence',
		'chastete',
		'mensonge',
		'colere',
		'avarice',
		'envie',
		'paresse',
		'orgueil',
		'gourmandise',
		'luxure',
		'suicide',
		'meurtre',
		'avortement',
		'euthanasie',
		'education',
		'travail',
		'argent',
		'propriete',
		'pauvrete',
		'richesse',
		'societe',
		'famille',
		'embryon',
		'noces',
		'jeunes',
		'jeunesse',
		'adolescence',
		'patrie',
		'inegalite',
		'opinion',
		'regulation',
		'talents',
		'douceur',
		'humilite',
		'obeissance',
		'pardon',
		'hospitalite',
		'charite fraternelle',
		'aumone',
		'jeune',
		'penitence',
		'satisfaction',
		'serment',
		'parjure',
		'racisme',
		'guerre',
		'paix sociale',
		'vocation',
		'accusation',
		'autopsie',
		'acharnement',
		'aveu',
		'exercice',
		'chomage',
		'demographie',
		'ecole',
		'inceste',
		'indigence',
		'individualisme',
		'jeux',
		'masturbation',
		'materialisme',
		'moribond',
		'notoriete',
		'oppression',
		'permissivite',
		'pornographie',
		'profanation',
		'progres',
		'promotion humaine',
		'prostitution',
		'race',
		'secret',
		'separation',
		'sobriete',
		'socialisation',
		'sterilisation',
		'sterilite',
		'syndicat',
		'terrorisme',
		'torture',
		'transmission',
		'transplantation',
		'usure',
		'viol',
		'mansuetude',
		'maitrise de soi',
		'crémation',
		'cremation',
		'epoux',
		'epouse',
		'mari',
		'maladie'
	],
	priere: [
		'priere',
		'oraison',
		'notre pere',
		'pater',
		'meditation',
		'contemplation',
		'benediction',
		'doxologie',
		'amen',
		'action de grace',
		'breviaire',
		'devotion',
		'kyrie',
		'litanies',
		'marana tha',
		'vepres',
		'mystique',
		'rosaire'
	],
	ecriture: [
		'ecriture',
		'bible',
		'evangile',
		'apotre',
		'apotres',
		'paul',
		'prophete',
		'prophetique',
		'inspiration',
		'canon',
		'testament',
		'pentateuque',
		'psaume',
		'kerygme',
		'tradition',
		'revelation',
		'babel',
		'deluge',
		'sanhedrin',
		'propitiation',
		'propitiatoire',
		'hebreux',
		'israel',
		'patriarche',
		'mythologie',
		'mythe',
		'septante',
		'typologie',
		'arche'
	],
	'marie-saints': [
		'marie',
		'mariale',
		'sainte vierge',
		'mere de dieu',
		'theotokos',
		'immaculee',
		'assomption',
		'saint',
		'sainte',
		'martyr',
		'canonisation',
		'angelique',
		'ange',
		'archange',
		'patriarche'
	],
	'fins-dernieres': [
		'mort',
		'jugement',
		'ciel',
		'paradis',
		'enfer',
		'purgatoire',
		'resurrection des morts',
		'eschatologie',
		'parousie',
		'fin du monde',
		'antichrist',
		'beatitude eternelle',
		'vie eternelle',
		'damnation',
		'salut',
		'limbes',
		'sheol',
		'recapitulation',
		'retribution',
		'eternite',
		'royaume des morts',
		'sejour des morts'
	]
};

// Hard overrides: the heuristic gets these wrong, so map the head-word
// directly. Keyed by lowercased+diacritic-stripped term.
export const CLUSTER_OVERRIDES: Record<string, ClusterId[]> = {
	dieu: ['trinite'],
	pere: ['trinite'],
	'pere notre': ['priere'],
	'notre pere': ['priere'],
	fils: ['christ', 'trinite'],
	verbe: ['christ', 'trinite'],
	christ: ['christ'],
	'esprit saint': ['esprit-saint'],
	trinite: ['trinite'],
	'tres sainte trinite': ['trinite'],
	eglise: ['eglise'],
	bapteme: ['sacrements'],
	confirmation: ['sacrements'],
	eucharistie: ['sacrements', 'liturgie'],
	penitence: ['sacrements'],
	reconciliation: ['sacrements'],
	'onction des malades': ['sacrements'],
	ordre: ['sacrements'],
	mariage: ['sacrements'],
	foi: ['morale'],
	esperance: ['morale'],
	charite: ['morale'],
	priere: ['priere'],
	conscience: ['morale'],
	'peche originel': ['creation-homme', 'morale'],
	peche: ['morale'],
	homme: ['creation-homme'],
	creation: ['creation-homme'],
	ame: ['creation-homme'],
	corps: ['creation-homme'],
	'image de dieu': ['creation-homme'],
	bible: ['ecriture'],
	evangile: ['ecriture'],
	tradition: ['ecriture', 'eglise'],
	revelation: ['ecriture'],
	marie: ['marie-saints'],
	saints: ['marie-saints'],
	'communion des saints': ['marie-saints', 'eglise'],
	mort: ['fins-dernieres'],
	resurrection: ['christ', 'fins-dernieres'],
	'jugement dernier': ['fins-dernieres'],
	ciel: ['fins-dernieres'],
	enfer: ['fins-dernieres'],
	purgatoire: ['fins-dernieres'],
	'vie eternelle': ['fins-dernieres'],
	paradis: ['fins-dernieres'],
	salut: ['fins-dernieres'],
	parousie: ['fins-dernieres'],
	avent: ['liturgie'],
	noel: ['liturgie'],
	paques: ['liturgie'],
	careme: ['liturgie'],
	pentecote: ['liturgie', 'esprit-saint'],
	dimanche: ['liturgie'],
	messe: ['liturgie', 'sacrements'],
	'annee liturgique': ['liturgie'],
	apotre: ['eglise'],
	apotres: ['eglise'],
	pape: ['eglise'],
	eveque: ['eglise'],
	pretre: ['eglise', 'sacrements'],
	concile: ['eglise'],
	magistere: ['eglise'],
	notre: ['priere'],
	vie: ['creation-homme'],
	'vie consacree': ['eglise'],
	'vie morale': ['morale'],
	'vie liturgique': ['liturgie'],
	'vie eternelle': ['fins-dernieres'],
	'vie de priere': ['priere'],
	'vie chretienne': ['morale'],
	'vie en christ': ['morale'],
	personne: ['creation-homme'],
	dignite: ['creation-homme'],
	religieux: ['eglise'],
	religieuses: ['eglise'],
	'religieux clergé': ['eglise'],
	catechumenat: ['sacrements'],
	'vigile pascale': ['liturgie'],
	eternite: ['fins-dernieres'],
	guerre: ['morale'],
	commerce: ['morale'],
	veuve: ['morale'],
	abel: ['ecriture'],
	cain: ['ecriture'],
	noe: ['ecriture'],
	moise: ['ecriture'],
	david: ['ecriture'],
	salomon: ['ecriture'],
	jean: ['ecriture'],
	paul: ['ecriture'],
	jerusalem: ['ecriture'],
	bethleem: ['ecriture'],
	'action de graces': ['priere'],
	'aveu des fautes': ['sacrements'],
	'rosaire': ['priere'],
	'collecte et sa signification': ['liturgie'],
	'option preferentielle': ['morale'],
	'transmission de la vie': ['morale'],
	'imputabilite des actions et des fautes': ['morale'],
	'jeux de hasard': ['morale'],
	'permissivite des moeurs': ['morale'],
	'maitrise de soi': ['morale'],
	'separation des epoux': ['morale'],
	'syndicats ouvriers': ['morale'],
	'transplantation d organes': ['morale'],
	'secrets professionnels': ['morale'],
	'exercices physiques': ['morale'],
	'instituts seculiers': ['eglise'],
	'humanisme chretien': ['eglise'],
	'religiosite populaire': ['priere'],
	'zele religieux': ['eglise'],
	'lex orandi': ['liturgie'],
	'kyrie eleison': ['liturgie'],
	'marana tha': ['priere'],
	'royaume de satan': ['fins-dernieres'],
	'retribution divine': ['fins-dernieres'],
	'endurcissement du coeur': ['morale'],
	'voeu votum religieux': ['eglise'],
	'voeu religieux': ['eglise'],
	'arbre du bien et du mal': ['ecriture'],
	'appreciation aestimatio du bien et du mal': ['morale'],
	'indifference religieuse': ['morale'],
	'indigence inopia et secours aux indigents': ['morale'],
	'iniquite': ['morale'],
	'mythologie mythe': ['ecriture'],
	'demographie': ['morale'],
	'azymes': ['liturgie'],
	'banquet': ['liturgie'],
	'hebreux': ['ecriture'],
	'paiens': ['ecriture'],
	'musulmans': ['eglise'],
	'reforme': ['eglise'],
	'ermite': ['eglise'],
	'royaute': ['christ'],
	'koinonia': ['eglise'],
	'sanhedrin': ['ecriture'],
	'futur': ['fins-dernieres'],
	'futur de l humanite': ['fins-dernieres'],
	'mystique': ['priere'],
	'connaissance': ['esprit-saint'],
	'sterilite': ['morale'],
	'sterilisation': ['morale'],
	'sobriete': ['morale'],
	'socialisation': ['morale'],
	'usure': ['morale'],
	'tortures': ['morale'],
	'oppression': ['morale'],
	'masturbation': ['morale'],
	'pornographie': ['morale'],
	'prostitution': ['morale'],
	'crémation': ['morale'],
	'cremation': ['morale'],
	'autopsie': ['morale'],
	'acharnement therapeutique': ['morale'],
	'moribonds': ['morale'],
	'multitude': ['ecriture'],
	'profanation': ['morale'],
	'magie': ['morale'],
	'individualisme': ['morale'],
	'materialisme': ['morale'],
	'inceste': ['morale'],
	'inegalite': ['morale'],
	'opinion publique': ['morale'],
	'progres': ['morale'],
	'promotion provectio humaine': ['morale'],
	'race': ['morale'],
	'racisme': ['morale'],
	'terrorisme': ['morale'],
	'viol': ['morale'],
	'chomage': ['morale'],
	'commerce': ['morale'],
	'argent': ['morale'],
	'jeunes': ['morale'],
	'adolescence': ['morale'],
	'patrie': ['morale'],
	'societes': ['morale'],
	'noces': ['sacrements'],
	'embryon humain': ['morale'],
	'regulation des naissances': ['morale'],
	'talents': ['morale'],
	'veuve': ['morale'],
	'suicide': ['morale'],
	'suffrages': ['fins-dernieres'],
	'limbes': ['fins-dernieres'],
	'sheol': ['fins-dernieres'],
	'recapitulation': ['christ'],
	'epiphanie': ['liturgie'],
	'dimanche': ['liturgie'],
	'vepres': ['priere'],
	'breviaire': ['priere'],
	'devotion': ['priere'],
	'dévotion': ['priere'],
	'litanies': ['priere'],
	'baptistere': ['liturgie'],
	'cimetiere': ['liturgie'],
	'ambon': ['liturgie'],
	'encens': ['liturgie'],
	'myron': ['liturgie'],
	'procession': ['liturgie'],
	'agnosticisme': ['trinite'],
	'atheisme': ['trinite'],
	'polytheisme': ['trinite'],
	'monotheisme': ['trinite'],
	'gnose': ['trinite'],
	'dualisme': ['trinite'],
	'kyrios': ['christ'],
	'sacre': ['liturgie'],
	'sens du sacre': ['liturgie'],
	'orthodoxie': ['eglise'],
	'orthodoxe': ['eglise'],
	'shabbat': ['liturgie'],
	'maladie': ['morale'],
	'mansuetude': ['morale'],
	'rectitude': ['morale'],
	'tristesse': ['morale'],
	'eternite': ['fins-dernieres'],
	'messianisme': ['fins-dernieres'],
	'millenarisme': ['fins-dernieres'],
	'votum religieux': ['eglise'],
	'voeu votum': ['eglise'],
	'armes': ['morale'],
	'decision': ['morale'],
	'ethique': ['morale'],
	'imagination': ['morale'],
	'victime': ['christ'],
	'necessiteux': ['morale'],
	'tristesse': ['morale'],
	'rectitude': ['morale'],
	'mansuetude': ['morale'],
	'troce': ['morale'],
	'trone': ['eglise'],
	'tete': ['christ'],
	'venielle': ['morale'],
	'veniel': ['morale'],
	'dux': ['eglise'],
	'election': ['morale'],
	'existence': ['creation-homme'],
	'hermeneutique': ['ecriture'],
	'livre': ['ecriture'],
	'message': ['eglise'],
	'moral': ['morale'],
	'oriental': ['eglise'],
	'relations': ['creation-homme'],
	'renommee': ['morale'],
	'retour': ['fins-dernieres'],
	'un': ['trinite'],
	'une': ['eglise']
};

function norm(s: string): string {
	return s
		.normalize('NFD')
		.replace(/[̀-ͯ]/g, '')
		.replace(/œ/g, 'oe')
		.replace(/Œ/g, 'OE')
		.replace(/æ/g, 'ae')
		.replace(/Æ/g, 'AE')
		.toLowerCase()
		.replace(/[’']/g, ' ')
		.replace(/[^a-z0-9]+/g, ' ')
		.replace(/\s+/g, ' ')
		.trim();
}

export function clusterFor(term: string, sampleSubLabels: string[] = []): ClusterId[] {
	const key = norm(term).trim();
	const ov = CLUSTER_OVERRIDES[key];
	if (ov) return ov;
	const haystack =
		key + ' ' + sampleSubLabels.slice(0, 6).map((s) => norm(s)).join(' ');
	const votes: Map<ClusterId, number> = new Map();
	for (const [cid, kws] of Object.entries(CLUSTER_KEYWORDS)) {
		for (const kw of kws) {
			if (haystack.includes(kw)) {
				votes.set(cid as ClusterId, (votes.get(cid as ClusterId) ?? 0) + 1);
			}
		}
	}
	if (votes.size === 0) return [];
	const sorted = [...votes.entries()].sort((a, b) => b[1] - a[1]);
	// Take top 1 unless second is within 1 vote, then take both.
	const out: ClusterId[] = [sorted[0]![0]];
	if (sorted.length > 1 && sorted[1]![1] >= sorted[0]![1] - 1 && sorted[1]![1] >= 2) {
		out.push(sorted[1]![0]);
	}
	return out;
}
