export type Corpus = 'ccc';

export interface BibleRef {
	text: string;
	book?: string;
	chapter?: number;
	verseStart?: number;
	verseEnd?: number;
}

export interface CrossRef {
	target: number;
	idx?: string;
}

export interface Citation {
	text_html: string;
	source?: MagisterialRefRecord;
}

export interface MagisterialRefRecord {
	type: 'magisterial' | 'patristic' | 'liturgical' | 'bible' | 'bible_continuation';
	abbr?: string;
	raw: string;
	idx?: string | number;
	doc_raw?: string;
}

export interface Paragraph {
	corpus: Corpus;
	number: number;
	text_html: string;
	cross_refs: string[];
	bible_refs: BibleRef[];
	citations: Citation[];
	magisterial_refs: MagisterialRefRecord[];
	parent_chapter_slug?: string;
}

export interface EnBrefBlock {
	parent_kind: 'chapter' | 'section';
	parent_slug: string;
	paragraphs: number[];
}

export interface Chapter {
	corpus: Corpus;
	slug: string;
	title: string;
	number?: number;
	part_slug: string;
	part_title: string;
	part_number?: number;
	section_slug: string;
	section_title: string;
	section_number?: number;
	paragraphs: number[];
	headings: ChapterHeading[];
	articles: ChapterArticle[];
	en_brefs: { paragraphs: number[] }[];
	prev?: { slug: string; title: string };
	next?: { slug: string; title: string };
}

export interface ChapterArticle {
	slug: string;
	title: string;
	number?: number;
	paragraphs: number[];
	headings: ChapterHeading[];
}

export interface ChapterHeading {
	id: string;
	level: number;
	title: string;
	paragraph_start: number;
}

export type StructureNodeType =
	| 'part'
	| 'section'
	| 'chapter'
	| 'article'
	| 'heading'
	| 'sub_heading';

export interface StructureNode {
	type: StructureNodeType | 'paragraph';
	title?: string;
	slug?: string;
	number?: number;
	children?: StructureNode[];
}

export interface ThematicEntry {
	letter: string;
	term: string;
	subentries: ThematicSubEntry[];
}

export interface ThematicSubEntry {
	label: string;
	paragraphs: number[];
}

export interface SourceEntry {
	category: string;
	doc_name: string;
	location: string;
	paragraphs: number[];
}

export type AbbreviationMap = Record<string, string>;

export interface ParagraphRange {
	from: number;
	to: number;
}

export interface BreadcrumbLevel {
	slug: string;
	title: string;
	number?: number;
	range?: ParagraphRange;
}

export interface ParagraphContext {
	part: BreadcrumbLevel;
	section?: BreadcrumbLevel;
	chapter?: BreadcrumbLevel;
	article?: BreadcrumbLevel;
	heading?: { id: string; title: string };
}

// Per-verse CCC citation lookup, generated by scripts/prepare/bible-verse-index.ts.
// Shape: usfx → chapter → verse → paragraph numbers (sorted asc, deduped).
export type BibleVerseIndex = Record<string, Record<string, Record<string, number[]>>>;

// One NCL Bible book's verse text. Shape: chapter → verse → text.
export type NclBook = Record<string, Record<string, string>>;

// Full NCL Bible verse text. Shape: usfx → chapter → verse → text.
export type NclBible = Record<string, NclBook>;

/** A French section title from the NCL Bible (e.g. "La faute et le châtiment"). */
export interface NclSection {
	ch: number; // chapter where the section header appears
	startV: number; // first verse of the section
	title: string; // already-French native title
	/** Parallel-passage cross-reference parenthetical text from <p style="r">
	 *  immediately following the section's <s>. Already includes outer parens.
	 *  null if the section has no associated cross-ref paragraph. */
	crossRefs: string | null;
}

/** Per-book sections, sorted by (ch asc, startV asc). */
export type NclSectionMap = Record<string, NclSection[]>; // keyed by USFX

/**
 * A contiguous CCC paragraph range. A bare paragraph number is `{from: n, to: n}`.
 * Source ranges like `337-354` are preserved as a single entry so the UI can
 * render them as one "337-354" chip linking to `/ccc/337-354`.
 */
export interface CccRange {
	from: number;
	to: number;
}

/**
 * A single Didache pericope: a verse range and its CCC paragraph references.
 * Title is the matching NCL section title (already French) or null.
 */
export interface ConcordancePericope {
	verseRef: string; // "Genèse 3:1-24"
	startCh: number;
	endCh: number;
	startVerse: number; // first verse in THIS chapter (for multi-chapter ranges, capped to chapter start)
	endVerse: number; // last verse in THIS chapter (capped to chapter end)
	pericopeTitle: string | null;
	pericopeCrossRefs: string | null; // parallel-passage parenthetical from the matched NCL section
	cccRanges: CccRange[]; // contiguous CCC ranges, sorted by `from` asc
}

/** Per-chapter file shape, mirroring DR's FathersChapterFile. */
export interface ConcordanceChapter {
	pericopes: ConcordancePericope[];
	verseEntryCounts: Record<number, number>; // verse → number of pericopes that cover it
	totalEntries: number;
}

/** by-paragraph inverse: which Bible passages reference each CCC paragraph. */
export interface ConcordanceByParagraphEntry {
	slug: string; // bible book slug, e.g. "genese"
	usfx: string; // "GEN"
	bookFrenchName: string; // "Genèse"
	chapter: number;
	verseRef: string; // "Genèse 3:1-24"
	pericopeTitle: string | null;
	pericopeCrossRefs: string | null; // parallel-passage parenthetical from the matched NCL section
	startCh: number;
	endCh: number;
	startVerse: number; // first verse of the pericope's first chapter
	endVerse: number; // last verse of the pericope's last chapter
	cccRanges: CccRange[]; // the pericope's full CCC ranges (post-filter, post-collapse)
}
export type ConcordanceByParagraph = Record<string, ConcordanceByParagraphEntry[]>;
// Keys are stringified paragraph numbers ("1850").

// Glossary (thematic index + Levada definitions). Built by
// scripts/prepare/glossary.ts.
export type GlossaryClusterId =
	| 'trinite'
	| 'christ'
	| 'esprit-saint'
	| 'eglise'
	| 'sacrements'
	| 'liturgie'
	| 'morale'
	| 'priere'
	| 'ecriture'
	| 'marie-saints'
	| 'fins-dernieres'
	| 'creation-homme';

export interface GlossarySubEntry {
	label: string;
	refs: number[];
}

export interface GlossaryEntry {
	slug: string;
	term: string;
	latin?: string;
	definition?: string;
	directRefs: number[];
	subEntries: GlossarySubEntry[];
	seeAlso: string[];
	clusters: GlossaryClusterId[];
	totalRefs: number;
	refsCovered: number[];
	standalone: boolean;
}

export interface GlossaryClusterMeta {
	id: GlossaryClusterId;
	label: string;
	short: string;
	description: string;
	order: number;
	count: number;
}

export interface GlossaryBundle {
	entries: GlossaryEntry[];
	clusters: GlossaryClusterMeta[];
	featured: string[]; // slugs of the top-cited entries
}
