export type Corpus = 'ccc';

export interface BibleRef {
	text: string;
	book?: string;
	chapter?: number;
	verseStart?: number;
	verseEnd?: number;
}

export interface CrossRef {
	target: number;
	idx?: string;
}

export interface Citation {
	text_html: string;
	source?: MagisterialRefRecord;
}

export interface MagisterialRefRecord {
	type: 'magisterial' | 'patristic' | 'liturgical' | 'bible' | 'bible_continuation';
	abbr?: string;
	raw: string;
	idx?: string | number;
	doc_raw?: string;
}

export interface Paragraph {
	corpus: Corpus;
	number: number;
	text_html: string;
	cross_refs: string[];
	bible_refs: BibleRef[];
	citations: Citation[];
	magisterial_refs: MagisterialRefRecord[];
	parent_chapter_slug?: string;
}

export interface EnBrefBlock {
	parent_kind: 'chapter' | 'section';
	parent_slug: string;
	paragraphs: number[];
}

export interface Chapter {
	corpus: Corpus;
	slug: string;
	title: string;
	number?: number;
	part_slug: string;
	part_title: string;
	part_number?: number;
	section_slug: string;
	section_title: string;
	section_number?: number;
	paragraphs: number[];
	headings: ChapterHeading[];
	articles: ChapterArticle[];
	en_brefs: { paragraphs: number[] }[];
	prev?: { slug: string; title: string };
	next?: { slug: string; title: string };
}

export interface ChapterArticle {
	slug: string;
	title: string;
	number?: number;
	paragraphs: number[];
	headings: ChapterHeading[];
}

export interface ChapterHeading {
	id: string;
	level: number;
	title: string;
	paragraph_start: number;
}

export type StructureNodeType = 'part' | 'section' | 'chapter' | 'article' | 'heading' | 'sub_heading';

export interface StructureNode {
	type: StructureNodeType | 'paragraph';
	title?: string;
	slug?: string;
	number?: number;
	children?: StructureNode[];
}

export interface ThematicEntry {
	letter: string;
	term: string;
	subentries: ThematicSubEntry[];
}

export interface ThematicSubEntry {
	label: string;
	paragraphs: number[];
}

export interface SourceEntry {
	category: string;
	doc_name: string;
	location: string;
	paragraphs: number[];
}

export type AbbreviationMap = Record<string, string>;

export interface ParagraphRange {
	from: number;
	to: number;
}

export interface BreadcrumbLevel {
	slug: string;
	title: string;
	number?: number;
	range?: ParagraphRange;
}

export interface ParagraphContext {
	part: BreadcrumbLevel;
	section?: BreadcrumbLevel;
	chapter?: BreadcrumbLevel;
	article?: BreadcrumbLevel;
	heading?: { id: string; title: string };
}

// Per-verse CCC citation lookup, generated by scripts/prepare/bible-verse-index.ts.
// Shape: usfx → chapter → verse → paragraph numbers (sorted asc, deduped).
export type BibleVerseIndex = Record<string, Record<string, Record<string, number[]>>>;

/**
 * Per-verse Catholic-concordance citation lookup, generated by
 * scripts/prepare/concordance.ts. Same shape as BibleVerseIndex but
 * sourced from a different citation graph and rendered as a distinct
 * (dotted-bordered) chip layer.
 */
export type ConcordanceVerseIndex = BibleVerseIndex;

// Glossary (thematic index + Levada definitions). Built by
// scripts/prepare/glossary.ts.
export type GlossaryClusterId =
	| 'trinite'
	| 'christ'
	| 'esprit-saint'
	| 'eglise'
	| 'sacrements'
	| 'liturgie'
	| 'morale'
	| 'priere'
	| 'ecriture'
	| 'marie-saints'
	| 'fins-dernieres'
	| 'creation-homme';

export interface GlossarySubEntry {
	label: string;
	refs: number[];
}

export interface GlossaryEntry {
	slug: string;
	term: string;
	latin?: string;
	definition?: string;
	directRefs: number[];
	subEntries: GlossarySubEntry[];
	seeAlso: string[];
	clusters: GlossaryClusterId[];
	totalRefs: number;
	refsCovered: number[];
	standalone: boolean;
}

export interface GlossaryClusterMeta {
	id: GlossaryClusterId;
	label: string;
	short: string;
	description: string;
	order: number;
	count: number;
}

export interface GlossaryBundle {
	entries: GlossaryEntry[];
	clusters: GlossaryClusterMeta[];
	featured: string[]; // slugs of the top-cited entries
}
